apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
  resourceName: custom-scheduler-mostallocated
  resourceNamespace: default
profiles:
- schedulerName: custom-scheduler-mostallocated
  pluginConfig: 
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta2
      kind: NodeResourcesFitArgs
      scoringStrategy:
        resources:
        - name: cpu
          weight: 1
        - name: memory
          weight: 1
        type: MostAllocated
    name: NodeResourcesFit
  plugins: 
    score:
      enabled:
      - name: NodeResourcesFit
        weight: 1
